# application.yml
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH}

server:
  port: ${SERVER_PORT}

logging:
  file:
    name: application.log

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example.todo: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.example.todo: INFO
    org.hibernate.SQL: INFO

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false